### ISSUE TITLE
Features I plan to pull request

### ISSUE THREAD

**Issue by karutt** [maxkrieger/figma-latex-complete-plugin#20]
## 1. Re-editing once-generated formulas

In the past, once a formula was generated, it was output as an svg and there was no way to edit it. Therefore, a re-editing function has been added.
    
1. select object → press edit button
2. select object → run plugin

You can now re-edit formulas in either of the above two ways.
![edit](https://user-images.githubusercontent.com/21274610/193402158-27e25315-a9af-47e5-a80f-05093472e1f7.gif)

## 2. Resizing the Plugin Window
    
Since there were some cases where the size of the plugin window was too small, such as when LaTeX Code is long, a function to resize the plugin window has been added at the lower right corner of the plugin window.
![resize](https://user-images.githubusercontent.com/21274610/193402167-f3f481d9-b78f-46dc-8f77-1ddea1a62755.gif)

## 3. Specify the font size of formulas

Previously, the width of the SVG output of formulas was always set to 200px, so if you wanted to output formulas with a certain font size, you had to manually change the size by eye. Therefore, we have added a feature that allows you to specify the font size when outputting.
![fs](https://user-images.githubusercontent.com/21274610/193402186-931c9b69-5f1c-4a68-91a9-03575f92e60d.gif)

## 4. Adding formulas to a selected node

Previously, the formula created did not belong to any node and was placed in the center of the display screen. Therefore, there was a hassle of moving the formula to the node you are currently working on. Now, when you select a FrameNode or GroupNode, run the plugin, and generate a formula, the formula will be added to the selected node.
![append](https://user-images.githubusercontent.com/21274610/193402198-802ee770-294f-469e-9d43-9e64a99146bc.gif)

## 5. Dark theme support
<img width="480" alt="dark_theme" src="https://user-images.githubusercontent.com/21274610/193402207-7db322d3-4dd7-4496-84cd-be48439d4a3a.png">

That's all.
Sorry that the text may be difficult to read, as I translated Japanese to English on a translation site.

**Comment by maxkrieger** [comment]
Wow, thank you so much! Please go ahead and send these in. ありがとう :)

**Comment by maxkrieger** [comment]
I have closed the issue, do use the discussions tab I opened for future announcements like these: https://github.com/maxkrieger/figma-latex-complete-plugin/discussions
